# Generated by Django 2.2 on 2019-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакты на главной странице',
                'verbose_name_plural': 'Контакты на главной странице',
            },
        ),
    ]
