# Generated by Django 2.2 on 2019-04-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_maincontacts_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название изображения в шапке',
                'verbose_name_plural': 'Названия изображений в шапке',
            },
        ),
    ]
