# Generated by Django 2.2 on 2019-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_mainimagetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение в шапке',
                'verbose_name_plural': 'Изображения в шапке',
            },
        ),
    ]
