# Generated by Django 2.2 on 2019-04-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=400, verbose_name='Номер или название этапа')),
                ('media', models.FileField(upload_to='build_step', verbose_name='Медиа')),
                ('title', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Номер или название этапа',
                'verbose_name_plural': 'Номер или название этапа',
            },
        ),
        migrations.CreateModel(
            name='KgObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=200, verbose_name='Название')),
                ('mini_image', models.ImageField(upload_to='mini_image', verbose_name='Мини Аватарка')),
                ('title', models.CharField(max_length=400, verbose_name='Краткое описание')),
                ('info', models.TextField(verbose_name='Полное описание')),
                ('status', models.CharField(choices=[('ready', 'Готовый'), ('planed', 'Запланированный'), ('progress', 'В процессе')], default='planed', max_length=40, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=500, verbose_name='Название Тега')),
                ('kg_object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_tag', to='main_page.KgObjects', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Теги',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ObjectGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='object_gallery', verbose_name='Медиа файл')),
                ('kg_object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gallery_object', to='main_page.KgObjects', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
