# Generated by Django 2.2 on 2019-04-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_buildstep_kgobjects_objectgallery_objecttags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='main_video', verbose_name='Видео')),
                ('title', models.CharField(max_length=100, verbose_name='Название видео')),
                ('image', models.ImageField(upload_to='video_image', verbose_name=' Изображение к видео')),
            ],
            options={
                'verbose_name': 'Видео на главной',
                'verbose_name_plural': 'Видео на главной',
            },
        ),
    ]
