# Generated by Django 2.2 on 2019-04-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
