# Generated by Django 2.2 on 2019-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_news_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgobjects',
            name='big_image',
            field=models.ImageField(blank=True, null=True, upload_to='big_image', verbose_name='Фото для шапки'),
        ),
    ]
