# Generated by Django 2.2 on 2019-04-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_kgobjects_big_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objecttags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='kgobjects',
            name='map',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка неа карту'),
        ),
    ]
