# Generated by Django 2.2 on 2019-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20190422_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgobjects',
            name='frame',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Ссылка на фрейм'),
        ),
    ]
