# Generated by Django 2.2 on 2019-04-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_kgobjects_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Дата архива')),
            ],
            options={
                'verbose_name': 'Архив благотворительности',
                'verbose_name_plural': 'Архивы благотворительности',
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('logo', models.ImageField(upload_to='charity_logo', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_date', models.DateField(verbose_name='Дата')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='charity', to='main_page.CharityArchive', verbose_name='Архив')),
            ],
            options={
                'verbose_name': 'Благотворительность',
                'verbose_name_plural': 'Благотворительности',
            },
        ),
    ]
