# Generated by Django 2.2 on 2019-04-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20190425_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст Kg'),
        ),
        migrations.AddField(
            model_name='charity',
            name='title_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок KG'),
        ),
        migrations.AddField(
            model_name='kgobjects',
            name='info_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Полное описание KG'),
        ),
        migrations.AddField(
            model_name='kgobjects',
            name='object_name_kg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название на КГ'),
        ),
        migrations.AddField(
            model_name='kgobjects',
            name='title_kg',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Краткое описание KG'),
        ),
        migrations.AddField(
            model_name='mainimagetitle',
            name='title_kg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название на КГ'),
        ),
        migrations.AddField(
            model_name='mainvideo',
            name='title_kg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название видео на КГ'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст новости KG'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок Kg'),
        ),
        migrations.AddField(
            model_name='objecttags',
            name='tag_name_kg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название Тега KG'),
        ),
    ]
