# Generated by Django 2.2 on 2019-04-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_auto_20190426_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_image', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст параграфа')),
                ('text_kg', models.TextField(verbose_name='Текст параграфа KG')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main_page.News', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Контент новостей',
                'verbose_name_plural': 'Контенты новостей',
            },
        ),
    ]
