# Generated by Django 2.2 on 2019-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0018_newscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Текст новости для главной'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст новости для главной KG'),
        ),
    ]
