# Generated by Django 2.2 on 2019-05-01 10:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_auto_20190430_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
