# Generated by Django 2.2 on 2019-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_auto_20190501_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Шапка для главной'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_kg',
            field=models.TextField(blank=True, null=True, verbose_name='Шапка для главной KG'),
        ),
    ]
