# Generated by Django 2.2 on 2019-05-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_auto_20190501_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscontent',
            options={'verbose_name': 'Изображение новостей', 'verbose_name_plural': 'Изображение новостей'},
        ),
    ]
