# Generated by Django 2.2 on 2019-05-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_auto_20190501_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='text_kg',
        ),
    ]
