# Generated by Django 2.2 on 2019-05-01 11:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0026_remove_news_text_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charitycontent',
            options={'verbose_name': 'Изображение Благотворительности', 'verbose_name_plural': 'Изображение Благотворительности'},
        ),
        migrations.RemoveField(
            model_name='charity',
            name='text',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='text_kg',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='charity',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='news',
            name='contents',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news_video', verbose_name='Видео новости')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='main_page.News', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео новостей',
                'verbose_name_plural': 'Видео новостей',
            },
        ),
        migrations.CreateModel(
            name='CharityVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='news_video', verbose_name='Видео Благотворительности')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='main_page.Charity', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Видео новостей',
                'verbose_name_plural': 'Видео новостей',
            },
        ),
    ]
